import { setCurrentUser, login } from './auth';
import { writeLog } from './logs';
import {
  getPersonnel,
  getDonVi,
  getNhaCungCap,
  getAnNinh,
  getXe,
  getChiPhiXe,
  getPhapNhan,
  getPhongHop,
  getQuyDinh,
  getThietBi,
  getNhatKyThietBi,
  getVanBan,
  getPVHC,
  getATVSLD,
  getPCTT,
  getPCCC,
  getTsPCCC,
  getUsers,
  getLogs,
  save,
  deleteRecord,
  getThueBao,
  getCuocThang,
  getKhoaHuanLuyen,
  getHocVienKhoaHuanLuyen,
  getChuKyATVSLD,
  getThietBiNghiemNgat,
  getKiemDinhTBNN,
  getNhatKySuDungXe
} from './modules';

export const apiService = {
  setCurrentUser,
  writeLog,
  login,
  getPersonnel,
  getDonVi,
  getNhaCungCap,
  getAnNinh,
  getXe,
  getChiPhiXe,
  getPhapNhan,
  getPhongHop,
  getQuyDinh,
  getThietBi,
  getNhatKyThietBi,
  getVanBan,
  getPVHC,
  getATVSLD,
  getPCTT,
  getPCCC,
  getTsPCCC,
  getUsers,
  getLogs,
  save,
  delete: deleteRecord,
  getThueBao,
  getCuocThang,
  getKhoaHuanLuyen,
  getHocVienKhoaHuanLuyen,
  getChuKyATVSLD,
  getThietBiNghiemNgat,
  getKiemDinhTBNN,
  getNhatKySuDungXe
};
